<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table_Sort-Car</name>
   <tag></tag>
   <elementGuidId>1e4b4050-a145-4b2b-9e67-20a0ac6b9fcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;resultTable&quot;]/thead/tr/th[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;resultTable&quot;]/thead/tr/th[7]</value>
   </webElementProperties>
</WebElementEntity>
