<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table_Sort-Diff</name>
   <tag></tag>
   <elementGuidId>381aa374-380f-4679-8aac-8208596d2bd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;resultTable&quot;]/thead/tr/th[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;resultTable&quot;]/thead/tr/th[10]</value>
   </webElementProperties>
</WebElementEntity>
